version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://btekinli:****@clustermern.50rmfjz.mongodb.net/
      - JWT_SECRET=uDteyK/QsU9HwWa3V1DRMi1ygIVKEDzEqSi8tO17OZE=
    volumes:
      - .:/app
    command: npm run dev
